name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main  # a branch que você está usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar version.txt com hash do commit
        run: echo "${{ github.sha }}" > version.txt

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # publica a raiz do repositório
